### ISSUE TITLE
Won't run on Amiga Forever Amiga 500

### ISSUE THREAD

**Issue by MihaMarkic** [coppersoft/rana#1]
Perhaps I'm doing something wrong, but the compiled app size is 550,624 bytes and as such it yields "Insufficient free store" when attempting to run on Amiga 500 UAE (Amiga Forever).
Is this by design?

**Comment by coppersoft** [comment]
Hi, sorry for the late response. You need at least 1 Mb of RAM.

By the way, RANA is now on aminet! 

https://aminet.net/package/game/jump/rana

Have fun!

**Comment by MihaMarkic** [comment]
Works, thanks.
